### ISSUE TITLE
Add date for experiences and schools

### ISSUE THREAD

**Issue by pa-decarvalho** [Paul-Riviere/mkdocs-curriculum-vitae#39]
Actually, experiences and schools and defined like that:

```yml
experiences:
  - title: First experience
    description: First experience description
  - title: Second experience
    description: Second experience description
schools:
  - title: First school
    description: First school description
  - title: Second school
    description: Second school description
```

It would be good to be able to define a date for this fileds like that :

```yml
experiences:
  - title: First experience
    date: 2019-04-13 to 2021-02-24
    description: First experience description
  ...
schools:
  - title: First school
    date: 2013-05-13 to 2015-06-14
    description: First school description
  - title: Certificat school
    date: 2016-05-13
    description: Certificat school
```

`date` parameter can be a specific date `2016-05-13` or a range `2013-05-13 to 2015-06-14`

It's just an example and date format can be changed, maybe use `date`, `start-date` and `end-date` fields ?
