### ISSUE TITLE
Add certifications section

### ISSUE THREAD

**Issue by pa-decarvalho** [Paul-Riviere/mkdocs-curriculum-vitae#41]
Like `experiences`, create a `certifications` sections :

```yml
  certifications:
    - title: First certification
      description: First certification description
    - title: Second certification
      description: Second certification description
```

**Comment by Paul-Riviere** [comment]
Do certifications really need a description ? Maybe some need a link to the certification.
Is is ok if for now we just add certification's title ?

**Comment by pa-decarvalho** [comment]
Yes of course only the link to the certification is enought.

For now it can only be like that :

```yml
certifications:
    - title: First certification
    - title: Second certification
```

In a future feature, it would be cool to include a link to official certification (such as a SCRUM badge).
