### ISSUE TITLE
Add hobbies section

### ISSUE THREAD

**Issue by pa-decarvalho** [Paul-Riviere/mkdocs-curriculum-vitae#43]
Like `experiences`, create a `hobbies` sections :

```yml
  hobbies:
    - title: First hobby
      description: First hobby description
    - title: Second hobby
      description: Second hobby description
```
